clausi_raidplaner_controller:
    pattern: /raidplaner/index
    defaults: { _controller: clausi.raidplaner.main.controller:index }

clausi_raidplaner_controller_view:
    pattern: /raidplaner/view/{raid_id}
    defaults: { _controller: clausi.raidplaner.main.controller:view, view: "0" }

clausi_raidplaner_controller_status:
    pattern: /raidplaner/status/{raid_id}/{status_id}
    defaults: { _controller: clausi.raidplaner.main.controller:setUserstatus, raid_id: "0", status_id: "0" }

clausi_raidplaner_controller_modstatus:
    pattern: /raidplaner/modstatus/{raid_id}
    defaults: { _controller: clausi.raidplaner.main.controller:setModstatus, raid_id: "0" }
