imports:
    - { resource: tables.yml }

services:
    clausi.raidplaner.controller:
        class: clausi\raidplaner\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    clausi.raidplaner.listener:
        class: clausi\raidplaner\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @config
        tags:
            - { name: event.listener }
