imports:
    - { resource: tables.yml }

services:
    clausi.raidplaner.controller:
        class: clausi\raidplaner\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    clausi.raidplaner.listener:
        class: clausi\raidplaner\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @config
        tags:
            - { name: event.listener }
    clausi.raidplaner.admin.controller:
        class: clausi\raidplaner\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
    cron.task.core.raidplaner:
        class: clausi\raidplaner\cron\task\core\raidplaner_cron
        arguments:
            - @config
            - @dbal.conn
            - @service_container
        calls:
            - [set_name, [cron.task.core.raidplaner_cron]]
        tags:
            - { name: cron.task }
    cron.task.core.raidplanerattendee:
        class: clausi\raidplaner\cron\task\core\raidplaner_cron_attendee
        arguments:
            - @config
            - @dbal.conn
            - @service_container
        calls:
            - [set_name, [cron.task.core.raidplaner_cron_attendee]]
        tags:
            - { name: cron.task }
