imports:
    - { resource: tables.yml }

services:
    clausi.raidplaner.main.controller:
        class: clausi\raidplaner\controller\main_controller
        arguments:
            - @config
            - @auth
            - @controller.helper
            - @dbal.conn
            - @template
            - @user
            - @request
            - @service_container
    clausi.raidplaner.listener:
        class: clausi\raidplaner\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @config
        tags:
            - { name: event.listener }
    clausi.raidplaner.admin.controller:
        class: clausi\raidplaner\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @auth
            - @service_container
            - @profilefields.type_collection
            - @clausi.raidplaner.main.controller
    cron.task.core.raidplaner:
        class: clausi\raidplaner\cron\task\core\raidplaner_cron
        arguments:
            - @config
            - @dbal.conn
            - @service_container
            - @clausi.raidplaner.main.controller
        calls:
            - [set_name, [cron.task.core.raidplaner_cron]]
        tags:
            - { name: cron.task }
