parameters:
    tables.clausi.raidplaner_raids: %core.table_prefix%rp_raids
    tables.clausi.raidplaner_schedule: %core.table_prefix%rp_schedule
    tables.clausi.raidplaner_attendees: %core.table_prefix%rp_attendees
    tables.clausi.raidplaner_logs: %core.table_prefix%rp_logs
    tables.clausi.raidplaner_events: %core.table_prefix%rp_events
